---

- import_tasks: variables.yml

- name: install nrpe
  package:
    name: '{{ nrpe_packages }}'
  register: nrpe_installed
  until: nrpe_installed is succeeded

- name: configure nrpe
  template:
    src: 'nrpe_{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.cfg.j2'
    dest: '/etc/nagios/nrpe.cfg'
    owner: '{{ nrpe_user }}'
    group: '{{ nrpe_group }}'
    mode: '0644'
  register: __nrpe_configuration

- name: enable nrpe service and assure it is started
  service:
    name: nrpe
    enabled: yes
    state: >-
      {{
        __nrpe_configuration.changed |
          default(False) |
          ternary("restarted", "started")
      }}
  tags:
    - service

...
