---

- name: Include OS-specific variables
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_os_family }}.yml'

- name: Define nrpe_packages.
  ansible.builtin.set_fact:
    nrpe_packages: '{{ __nrpe_packages | list }}'
  when: nrpe_packages is not defined

...
